fix

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -2,12 +2,13 @@ name: LLM Conversation Bot
 
 on: [push]
 
+env:
+  SUCCESS_FILE: /home/sergx/tmp/git-pull-success__llm_conv_bot.txt
+  ERROR_FILE: /home/sergx/tmp/git-pull-error__llm_conv_bot.txt
+
 jobs:
   run_ssh_command:
     runs-on: ubuntu-latest
-    env:
-      SUCCESS_FILE: /home/sergx/tmp/git-pull-success__llm_conv_bot.txt
-      ERROR_FILE: /home/sergx/tmp/git-pull-error__llm_conv_bot.txt
     steps:
       - run: echo "🎉 The job was automatically triggered."
 
@@ -19,10 +20,12 @@ jobs:
           password: ${{ secrets.PRODUCTION_PASSWORD }}
           port: ${{ secrets.PRODUCTION_PORT }}
           script: |
-            cd llm_conversations_bot
+            mkdir -p /home/sergx/tmp
+
+            cd llm_conversations_bot || { echo "❌ Folder not found"; exit 1; }
 
             # Run git pull and capture stdout/stderr separately
-            { git pull 2>&1 > /home/sergx/tmp/git-pull-success__llm_conv_bot.txt || echo "Git pull failed" > /home/sergx/tmp/git-pull-error__llm_conv_bot.txt;}
+            git pull >"$SUCCESS_FILE" 2>"$ERROR_FILE"
 
             sudo systemctl restart llm_conversations_bot.service
 
@@ -31,21 +34,17 @@ jobs:
               local max_length=4096
               while [ -n "$message" ]; do
                 chunk="${message:0:max_length}"
-                curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+                curl -sS -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                   -d chat_id=${{ vars.TELEGRAM_CHAT_ID }} \
-                  -d text="$chunk"
+                  --data-urlencode text="$chunk"
                 message="${message:max_length}"
               done
             }
 
-            if [ -s /home/sergx/tmp/git-pull-error__llm_conv_bot.txt ]; then
-              send_telegram "❌ Deployment failed"
-              send_telegram "$(cat /home/sergx/tmp/git-pull-error__llm_conv_bot.txt)"
+            if [ -s "$ERROR_FILE" ]; then
+              send_telegram "❌ Deployment failed\n$(cat "$ERROR_FILE")"
             fi
 
-            if [ -s /home/sergx/tmp/git-pull-success__llm_conv_bot.txt ]; then
-              send_telegram "✅ Deployment success"
-              send_telegram "$(cat /home/sergx/tmp/git-pull-success__llm_conv_bot.txt)"
+            if [ -s "$SUCCESS_FILE" ]; then
+              send_telegram "✅ Deployment success\n$(cat "$SUCCESS_FILE")"
             fi
-
-
